### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by Yuelioi** [Utmost-Happiness-Planet/nonebot-plugin-repeater#18]
以下都在复读次数为2的情况下

1. 发一张图片也莫名其妙复读了(小概率事件)
2. 能不能不要复读指令,比如老有人发setu指令,机器人也会复读 不是(
3. 人类复读4次,机器人会复读2次,不太合理,连续复读最好只复读一次?

**Comment by ninthseason** [comment]
没注意到这个issue，刚刚翻邮件时才发现。

近期（一年半载）会比较繁忙，无暇更新插件，有空我会排查bug的。

**Comment by SakuraPuare** [comment]
对于你提出的第一个问题
> 发一张图片也莫名其妙复读了(小概率事件)

代码实现就是会复读图片，如果出现虚空复读的现象请附加更多信息

**Comment by SakuraPuare** [comment]
对于你提出的第二个 enhancement
> 不复读指令

已在[✨ feat: 添加复读黑名单](https://github.com/Utmost-Happiness-Planet/nonebot-plugin-repeater/commit/af6cd3ad99a100d4316f7b31ca9f6016136027f8) 中添加黑名单

**Comment by SakuraPuare** [comment]
对于你提出的第三个问题
> 连续复读只复读一次

完全相同的文字只会最多复读`repeater_min_message_times`次，若出现多次复读情况，请检查发现送的消息类型。
若确定这是一个bug，请再跟进信息

**Comment by ninthseason** [comment]
> 对于你提出的第三个问题
> 
> > 连续复读只复读一次
> 
> 完全相同的文字只会最多复读`repeater_min_message_times`次，若出现多次复读情况，请检查发现送的消息类型。 若确定这是一个bug，请再跟进信息

错误的，你再看看代码
