### ISSUE TITLE
关于复读图片，即使不是相同的图片也会复读的问题

### ISSUE THREAD

**Issue by laognf95** [Utmost-Happiness-Planet/nonebot-plugin-repeater#20]
```py
# nonebot_plugin_repeater/__init__.py line 24
contained_images.update({i: [re.findall(r'url=(.*?)[,\]]', i)[0][0], re.findall(r'file=(.*?)[,\]]', i)[0][0]]})
```
re.findall返回了所有匹配到的图片file链接的列表，取了索引为0的结果，然后再次取[0]，实际上返回的是字符串的第一个字符，导致实际每一次返回的都是[h]（也就是匹配到的```http://gchat.qpic.cn/...```的第一个字符h）

我尝试使用这个pattern去匹配
```py
...
pattern = r'file=http://gchat.qpic.cn/gchatpic_new/\d+/\d+-\d+-(.*?)/.*?[,\]]'
for i in images:
    contained_images.update({i: [re.findall(r'url=(.*?)[,\]]', i)[0], re.findall(pattern, i)[0]]})
```
似乎能正常工作，不过只是简单的测试了一下，姑且当作抛砖引玉了

**Comment by ninthseason** [comment]
好久没用机器人了，感觉应该是nonebot2更新了太多，这个老插件不兼容了吧。

**Comment by ninthseason** [comment]
现在应该也没人有时间维护这个库了，我也没有开发环境。要么提个pr我merge上去？

**Comment by ninthseason** [comment]
好像是我的一次提交引入的bug。

居然一直没发现。

![Screenshot_2024-03-14-14-43-29-461_com android browser](https://github.com/Utmost-Happiness-Planet/nonebot-plugin-repeater/assets/29861280/2bc2b4fa-53ca-491f-a5d2-b1f27195f685)

**Comment by ninthseason** [comment]
已merge
